[package]
name = "gtk4_ex"
version = "0.1.0"
edition = "2024"

[dependencies]
gettext-rs = { version = "0.8", features = ["gettext-system"] }
gtk = { version = "0.11", package = "gtk4", features = ["gnome_50"]  }
glib = { version = "0.21"}
futures = "0.3"
gio = "0.21"
tempfile = "3"
gdk4 = "0.10"
reqwest = "0.13"
tokio = { version = "1", features = ["rt", "rt-multi-thread"] }
[dependencies.adw]
package = "libadwaita"
version = "0.9"
features = ["v1_10"]
