use crate::baseplugin;

pub fn get_all_launcher() -> &'static  [baseplugin::base::LauncherFileInfo] {
    let all_ = &[
            baseplugin::base::LauncherFileInfo{
                                                laucher_file_name   : "com.github.yucefsourani.albasheer-electronic-quran-browser.desktop",
                                                type_               : baseplugin::base::PluginType::Launcher,
                                                category            : baseplugin::base::Category::Launcher,
                                                arch                : &["all"],
                                                distro_name         : &["all"],
                                                distro_version      : &["all"],
                                                desktop_env         : &["all"],
                                                display_type        : &["all"],
                                                icon_name           : "UNKNOW",
                                                custom_button_label : None,// Option<&'static str>,
                                                },
            baseplugin::base::LauncherFileInfo{
                                                laucher_file_name   : "com.mattjakeman.ExtensionManager.desktop",
                                                type_               : baseplugin::base::PluginType::Launcher,
                                                category            : baseplugin::base::Category::Launcher,
                                                arch                : &["all"],
                                                distro_name         : &["all"],
                                                distro_version      : &["all"],
                                                desktop_env         : &["gnome"],
                                                display_type        : &["all"],
                                                icon_name           : "UNKNOW",
                                                custom_button_label : None,// Option<&'static str>,
                                                },
            baseplugin::base::LauncherFileInfo{
                                                laucher_file_name   : "page.tesk.Refine.desktop",
                                                type_               : baseplugin::base::PluginType::Launcher,
                                                category            : baseplugin::base::Category::Launcher,
                                                arch                : &["all"],
                                                distro_name         : &["all"],
                                                distro_version      : &["all"],
                                                desktop_env         : &["gnome"],
                                                display_type        : &["all"],
                                                icon_name           : "UNKNOW",
                                                custom_button_label : None,// Option<&'static str>,
                                                },
            baseplugin::base::LauncherFileInfo{
                                                laucher_file_name   : "io.github.realmazharhussain.GdmSettings.desktop",
                                                type_               : baseplugin::base::PluginType::Launcher,
                                                category            : baseplugin::base::Category::Launcher,
                                                arch                : &["all"],
                                                distro_name         : &["all"],
                                                distro_version      : &["all"],
                                                desktop_env         : &["gnome"],
                                                display_type        : &["all"],
                                                icon_name           : "UNKNOW",
                                                custom_button_label : None,// Option<&'static str>,
                                                },
            baseplugin::base::LauncherFileInfo{
                                                laucher_file_name   : "io.github.kolunmi.Bazaar.desktop",
                                                type_               : baseplugin::base::PluginType::Launcher,
                                                category            : baseplugin::base::Category::Launcher,
                                                arch                : &["all"],
                                                distro_name         : &["all"],
                                                distro_version      : &["all"],
                                                desktop_env         : &["all"],
                                                display_type        : &["all"],
                                                icon_name           : "UNKNOW",
                                                custom_button_label : None,// Option<&'static str>,
                                                },

            baseplugin::base::LauncherFileInfo{
                                                laucher_file_name   : "com.github.tchx84.Flatseal.desktop",
                                                type_               : baseplugin::base::PluginType::Launcher,
                                                category            : baseplugin::base::Category::Launcher,
                                                arch                : &["all"],
                                                distro_name         : &["all"],
                                                distro_version      : &["all"],
                                                desktop_env         : &["all"],
                                                display_type        : &["all"],
                                                icon_name           : "UNKNOW",
                                                custom_button_label : None,// Option<&'static str>,
                                                },
            baseplugin::base::LauncherFileInfo{
                                                laucher_file_name   : "io.github.sitraorg.sitra.desktop",
                                                type_               : baseplugin::base::PluginType::Launcher,
                                                category            : baseplugin::base::Category::Launcher,
                                                arch                : &["all"],
                                                distro_name         : &["all"],
                                                distro_version      : &["all"],
                                                desktop_env         : &["all"],
                                                display_type        : &["all"],
                                                icon_name           : "UNKNOW",
                                                custom_button_label : None,// Option<&'static str>,
                                                },
            
            ];
    all_
}
