use crate::baseplugin;

pub fn get_all_website_plugins() -> &'static  [baseplugin::base::WebsiteInfo] {
    let all_ = &[
            baseplugin::base::WebsiteInfo{
                                                link                : "https://www.linuxac.org/",
                                                title               : "Linuxac",
                                                subtitle            : "مجتمع لينكس العربي",
                                                type_               : baseplugin::base::PluginType::Website,
                                                category            : baseplugin::base::Category::Website,
                                                arch                : &["all"],
                                                distro_name         : &["all"],
                                                distro_version      : &["all"],
                                                desktop_env         : &["all"],
                                                display_type        : &["all"],
                                                icon_name           : "linuxac.jpg", 
                                                custom_button_label : None,// Option<&'stati>,
                                                },
            baseplugin::base::WebsiteInfo{
                                                link                : "https://aosus.org/",
                                                title               : "aosus",
                                                subtitle            : "مجتمع أسس يهدف لنشر وإثراء ثقافة البرمجيات الحرة والمفتوحة في العالم العربي",
                                                type_               : baseplugin::base::PluginType::Website,
                                                category            : baseplugin::base::Category::Website,
                                                arch                : &["all"],
                                                distro_name         : &["all"],
                                                distro_version      : &["all"],
                                                desktop_env         : &["all"],
                                                display_type        : &["all"],
                                                icon_name           : "aosus.png", 
                                                custom_button_label : None,// Option<&'stati>,
                                                },
            baseplugin::base::WebsiteInfo{
                                                link                : "https://arfedora.blogspot.com",
                                                title               : "Blog Arfedora",
                                                subtitle            : "Arabic Blog For Fedora Linux",
                                                type_               : baseplugin::base::PluginType::Website,
                                                category            : baseplugin::base::Category::Website,
                                                arch                : &["all"],
                                                distro_name         : &["all"],
                                                distro_version      : &["all"],
                                                desktop_env         : &["all"],
                                                display_type        : &["all"],
                                                icon_name           : "NONE",
                                                custom_button_label : None,// Option<&'stati>,
                                                },
            baseplugin::base::WebsiteInfo{
                                                link                : "https://discussion.fedoraproject.org/",
                                                title               : "Fedora Discussion",
                                                subtitle            : "Fedora Project community discussion happens here!",
                                                type_               : baseplugin::base::PluginType::Website,
                                                category            : baseplugin::base::Category::Website,
                                                arch                : &["all"],
                                                distro_name         : &["fedora"],
                                                distro_version      : &["all"],
                                                desktop_env         : &["all"],
                                                display_type        : &["all"],
                                                icon_name           : "fedora-logo-sprite.png",
                                                custom_button_label : None,// Option<&'stati>,
                                                },
            baseplugin::base::WebsiteInfo{
                                                link                : "https://fedoramagazine.org/",
                                                title               : "Fedora Magazine",
                                                subtitle            : "Fedora Magazine is a WordPress-based site which delivers all the news of the Fedora Community.",
                                                type_               : baseplugin::base::PluginType::Website,
                                                category            : baseplugin::base::Category::Website,
                                                arch                : &["all"],
                                                distro_name         : &["fedora"],
                                                distro_version      : &["all"],
                                                desktop_env         : &["all"],
                                                display_type        : &["all"],
                                                icon_name           : "fedora-logo-sprite.png",
                                                custom_button_label : None,// Option<&'stati>,
                                                },
            baseplugin::base::WebsiteInfo{
                                                link                : "https://fedoraproject.org/",
                                                title               : "Fedora Project",
                                                subtitle            : "The Fedora Project is a community of people working together to build a free and open source software platform and to collaborate on and share user-focused solutions built on that platform.",
                                                type_               : baseplugin::base::PluginType::Website,
                                                category            : baseplugin::base::Category::Website,
                                                arch                : &["all"],
                                                distro_name         : &["fedora"],
                                                distro_version      : &["all"],
                                                desktop_env         : &["all"],
                                                display_type        : &["all"],
                                                icon_name           : "fedora-logo-sprite.png",
                                                custom_button_label : None,// Option<&'stati>,
                                                },
            baseplugin::base::WebsiteInfo{
                                                link                : "https://docs.fedoraproject.org/en-US/quick-docs/",
                                                title               : "Fedora Quick Docs",
                                                subtitle            : "This is a collection of short HOW-TO and FAQ-style documentation for Fedora users.",
                                                type_               : baseplugin::base::PluginType::Website,
                                                category            : baseplugin::base::Category::Website,
                                                arch                : &["all"],
                                                distro_name         : &["fedora"],
                                                distro_version      : &["all"],
                                                desktop_env         : &["all"],
                                                display_type        : &["all"],
                                                icon_name           : "fedora-logo-sprite.png",
                                                custom_button_label : None,// Option<&'stati>,
                                                },
            ];
    all_
}
