pub mod all_launcher;
pub mod xdm;
pub mod albasheer;

//pub use firefox::Plugin;
pub mod all_website_plugins;
pub mod arduinoide;
pub mod arduinoidev2;
pub mod ciano;
pub mod fritzing;
pub mod gitkraken;
pub mod handbrake;
pub mod marker;
pub mod mypaint;
pub mod pulseeffects;
pub mod vidcutter;
pub mod android_studio;
pub mod anydesk;
pub mod audacity_freeworld_fedora;
